## This file generated by InlineX::C2XS (version 0.17) using Inline::C (version 0.46_02)
package Math::GMPf::Random;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Math::GMPf::Random::VERSION = '0.33';

DynaLoader::bootstrap Math::GMPf::Random $Math::GMPf::Random::VERSION;

@Math::GMPf::Random::EXPORT = ();
@Math::GMPf::Random::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
