## This file generated by InlineX::C2XS (version 0.22) using Inline::C (version 0.5002)
package Math::GMPf::V;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Math::GMPf::V::VERSION = '0.35';

DynaLoader::bootstrap Math::GMPf::V $Math::GMPf::V::VERSION;

@Math::GMPf::V::EXPORT = ();
@Math::GMPf::V::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
